language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

env:
  - PROJECT_DIR=lazy
  - PROJECT_DIR=ftp

before_install: 
- cd $PROJECT_DIR
- chmod +x ./gradlew