language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

env:
  - PROJECT_DIR=lazy
  - PROJECT_DIR=vcs
  - PROJECT_DIR=ftp
  - PROJECT_DIR=MyJUnit

before_install: 
- cd $PROJECT_DIR
- chmod +x ./gradlew